config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/panel', to: 'panels#index', as: 'panel'
  get '/contact', to: 'application#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #,:confirmable
  mount_uploader :photo,AvatarUploader
  mount_uploader :pan_data,AvatarUploader
  mount_uploader :address_data, AvatarUploader
  after_create :generate_unique_id

  def generate_unique_id
  	
  	self.unique_id = Time.now.strftime("%d%m%y") + self.id.to_s  
        begin
          w_add = BlockIo.get_new_address(:label => self.unique_id.to_s)  
    rescue Exception=>e
           w_address =  BlockIo.get_address_by_label(:label => self.unique_id.to_s) 
      ensure
           w_address =  BlockIo.get_address_by_label(:label => self.unique_id.to_s) 

    end
  	self.save!
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home, :about, :contact]

  def home
      
     @approved_users = User.where(:is_approved => true ,:is_admin => false)
     @total_users = User.where(:is_admin => false)
    begin
     w_add = BlockIo.get_new_address(:label => current_user.unique_id.to_s)  
    rescue Exception=>e
           @w_address =  BlockIo.get_address_by_label(:label => current_user.unique_id.to_s) if current_user.present?
      ensure
           @w_address =  BlockIo.get_address_by_label(:label => current_user.unique_id.to_s) if current_user.present?

    end
  end

  def about

  end

  def contact
  end

  def secret
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,:photo,:pan,:ifsc,:address_data,:pan_data,:phone_number,:acc_no,:country,:state,:city,:unique_id])
  end
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController

	def index
		@users = User.where(:is_admin => false)
		  @approved_users = User.where(:is_approved => true ,:is_admin => false)
		 @total_users = User.where(:is_admin => false)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <p>#{sentence}</p>
    <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/views/application/about.html.slim
= content_for :title do
  = 'About'

.text-center
  h1 About
  p.text-success about details goes here

app/views/application/contact.html.slim
= content_for :title do
  = 'Contact'

.text-center
  h1 Contact
  p.text-success contact details goes here

app/views/application/home.html.erb
<div class='text-center'>

  <%if current_user.present? && !current_user.is_admin%>
    <div class="row">
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title"><%=current_user.first_name %></h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body">Unique Id : <%= current_user.unique_id%></div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">Wallet address</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<%if @w_address.present?%>
				<div class="panel-body"><%=@w_address["data"]["address"] if @w_address.present?%></div>
				<%else%>
				<div class="panel-body">WALLET ADDRESS CANNOT BE GENERATED, CONTACT ADMIN!</div>
				<%end%>
				
		</div>
	</div>
		<div class="row">
		<div class="col-md-6">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">LaxiPay Wallet</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body">Balance 0.0000</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">Your INR Balance</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body">0.0</div>
			</div>
		</div>
	</div>

			<div class="row">
		<div class="col-md-6">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">Account status</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body"><input class="btn btn-danger btn-lg" value="Not Verified"></div>
			</div>
		</div>
	</div>	
	</div>
	<%elsif current_user.present? && current_user.is_admin %>
	  <h1> Admin! </h1>
  			<p class='text-success'> Welcome</p>
	   <div class="row">
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Total Approved Users present</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body"> <%= @approved_users.count %></div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">Total Users present</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>

				<div class="panel-body"><%= @total_users.count %></div>
				
		</div>
	</div>

	</div>
	<% else %>
	<h1> LaxmiPay </h1>
	<p class='text-success'> Welcome</p>
  <%end%>
  
</div>

<style>
.row{
    margin-top:40px;
    padding: 0 10px;
}

.clickable{
    cursor: pointer;   
}

.panel-heading span {
	margin-top: -20px;
	font-size: 15px;
}
</style>
<script type="text/javascript">
	
	$(document).on('click', '.panel-heading span.clickable', function(e){
    var $this = $(this);
	if(!$this.hasClass('panel-collapsed')) {
		$this.parents('.panel').find('.panel-body').slideUp();
		$this.addClass('panel-collapsed');
		$this.find('i').removeClass('glyphicon-chevron-up').addClass('glyphicon-chevron-down');
	} else {
		$this.parents('.panel').find('.panel-body').slideDown();
		$this.removeClass('panel-collapsed');
		$this.find('i').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
	}
})
</script>

app/views/application/secret.html.slim
= content_for :title do
  = 'Secret'

.text-center
  h1 Secret
  p.text-success only logged in user can access this page

app/views/layouts/_navigation.html.slim
ul class="nav navbar-nav"
  li= link_to('<span class="glyphicon glyphicon-home"></span> Home'.html_safe, root_path)
  //li#= link_to('<span class="glyphicon glyphicon-lock"></span> Secret'.html_safe, secret_path)
  //li#= link_to('<span class="glyphicon glyphicon-phone-alt"></span> Contact'.html_safe, contact_path)
  - if current_user.present? && current_user.is_admin
    li= link_to('<span class="glyphicon glyphicon-user"></span> Users'.html_safe, panel_path)

ul class="nav navbar-nav navbar-right"
  - if current_user
    li= link_to('<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, edit_user_registration_path)
    li= link_to('<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, method: 'delete')
  - else
    li= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path)
    li= link_to('<span class="glyphicon glyphicon-saved"></span> Register'.html_safe, new_user_registration_path)

app/views/layouts/_notifications.html.slim
- if notice
  .alert.alert-info
    p= notice

- if alert
  .alert.alert-warning
    p= alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= content_for?(:title) ? yield(:title) + " - #{APPLICATION_NAME}" : "#{APPLICATION_NAME}" %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>

  </head>

  <body>
	  <nav class="navbar navbar-default">
		  <div class="container-fluid">
			  <div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed"
				          data-toggle="collapse" data-target="#menu-collapse">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
				  </button>
				  <%= link_to APPLICATION_NAME, root_path, class: 'navbar-brand' %>
			  </div>

			  <div class="collapse navbar-collapse" id="menu-collapse">

				  <%= render 'layouts/navigation' %>

			  </div>
		  </div>
	  </nav>

	  <div class="container">
		  <%= render 'layouts/notifications' %>

      <%= yield %>
	  </div>
  </body>
</html>

app/views/panels/index.html.erb
<div class="container">
    <h1>List of Users <small>(<i class="glyphicon glyphicon-filter"></i>)</small></h1>
    	<div class="row">
	
			<div class="col-md-12">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h3 class="panel-title">Users</h3>
						<div class="pull-right">
							<span class="clickable filter" data-toggle="tooltip" title="Toggle table filter" data-container="body">
								<i class="glyphicon glyphicon-filter"></i>
							</span>
						</div>
					</div>
					<div class="panel-body">
						<input type="text" class="form-control" id="task-table-filter" data-action="filter" data-filters="#task-table" placeholder="Filter Tasks" />
					</div>
					<table class="table table-hover" id="task-table">
						<thead>
							<tr>
								<th>#Unique id</th>
								<th>Name</th>
								<th>Wallet address</th>
								
								<th>Available Balance</th>
								<th>Pending recieved balance</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>

						<%@users.each do |user|%>
							<tr>
								<td><%= user.unique_id%></td>
								<td><%= user.first_name + '' + user.last_name%></td>
								<td><%w_a =  BlockIo.get_address_by_label :label => user.unique_id.to_s%>
						<%=		w_a["data"]["address"]						%></td>
<td>
						<%=		w_a["data"]["available_balance"]						%></td>
						<td>
						<%=		w_a["data"]["pending_received_balance"]						%></td>
								<%if user.is_approved%>
								<td><input class="btn btn-success btn-lg" value=" Verified"></td>
								<%else%>
								<td><input class="btn btn-danger btn-lg" value="Not Verified"></td>
								<%end%>
							</tr>
							<%end%>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

<style>
.row {
	margin-top: 40px;
	padding: 0 10px;
}
.clickable {
	cursor: pointer;
}
.panel-body {
	display: none;
}
.panel-heading div {
	margin-top: -18px;
	font-size: 15px;
	span {
		margin-left: 5px;
	}
}
</style>